/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Pages;

import Db.DB;
import Objects.Evento;
import UI.Components.CellAction;
import UI.Components.CellFecha;
import UI.Components.CellHora;
import UI.Components.CellName;
import UI.Models.ModelStaff;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author teval
 */
public class AllEvents extends javax.swing.JPanel {

    /**
     * Creates new form AllEvents
     */
    public AllEvents() {
        initComponents();
        setOpaque(false);        
        initTable();
        table1.addTableStyle(jScrollPane1); 
        table1.redimensionTable();
    }
    
    public void initTable(){
        table1.setModel(new DefaultTableModel(
            null ,
            new String [] {
                "ID", "EVENTO", "FECHA FIN", "HORA FIN", "TIEMPO", "NOTIFICACIONES", "ACTIONS"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               if(column==6) return true;
               return false;
            }
        });
        
        int cols=table1.getColumnCount();       
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);        
        
        for (int i = 0;i<cols; i++) {
            table1.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }        
        
        table1.addTableCell(new CellAction(), 6);
        table1.redimensionTable();
        table1.setName("Actuals");
    }
    
    public void llenarTabla(){       
        //llenar primero la tabla y despues limpiar los datos viejos
        ArrayList <Evento> evts = DB.getEventos();         
        limpiarTabla();
        for(int i=0; i<evts.size(); i++){
            Evento evento = evts.get(i);
            if(evento.isState()){
                table1.addRow(new ModelStaff(String.valueOf(i), evento.getNombre(), evento.getFechaFin().toInstant().toString().split("T")[0], evento.parseTimeToString(), evento.getTiempoFaltante(), evento.isIsNotify() ? "Notificaciones":"Sin Notificaciones"), false);
            }
        }                  
    }
    
    public void limpiarTabla(){
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new UI.Components.Table();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private UI.Components.Table table1;
    // End of variables declaration//GEN-END:variables
}
