/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Pages;

import Db.DB;
import Objects.Evento;
import UI.Components.CellAction;
import UI.Components.CellFecha;
import UI.Components.CellHora;
import UI.Components.CellName;
import UI.Models.ModelStaff;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author teval
 */
public class AllEvents extends javax.swing.JPanel {

    /**
     * Creates new form AllEvents
     */
    public AllEvents() {
        initComponents();
        setOpaque(false);        
        initTable();
        table1.addTableStyle(jScrollPane1); 
    }
    
    public void initTable(){
        table1.setModel(new DefaultTableModel(
            null ,
            new String [] {
                "ID", "EVENTO", "FECHA FIN", "HORA FIN", "TIEMPO", "NOTIFICACIONES", "ACTIONS"
            }
        ));
        
        DefaultTableModel modelo=(DefaultTableModel) table1.getModel();
        int cols=table1.getColumnCount();       
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.CENTER);        
        
        for (int i = 0;i<cols; i++) {
            table1.getColumnModel().getColumn(i).setCellRenderer(tcr);
        }
        
        table1.addTableCell(new CellName(), 1);
        table1.addTableCell(new CellFecha(), 2);
        table1.addTableCell(new CellHora(), 3);
        table1.addTableCell(new CellAction(), 6);
    }
    
    public void llenarTabla(){       
        
        ArrayList <Evento> evts = DB.getEventos();         
        
        limpiarTabla();
        
        for(int i=0; i<evts.size(); i++){
            Evento evento = evts.get(i);
            if(evento.isState()){
                table1.addRow(new ModelStaff(String.valueOf(0), evento.getNombre(), String.valueOf(evento.getFechaFin()), String.valueOf(evento.getHoraFin()), evento.getTiempoFaltante(), evento.isIsNotify() ? "Notificaciones":"Sin Notificaciones"), false);
            }
        }                               
    }
    
    public void limpiarTabla(){
        try {
            
            DefaultTableModel modelo=(DefaultTableModel) table1.getModel();
            int filas=table1.getRowCount();
            for (int i = 0;i<filas; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            System.out.println("Error al limpiar tabla");
            throw new Error(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new UI.Components.Table();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private UI.Components.Table table1;
    // End of variables declaration//GEN-END:variables
}
