/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Pages;

import UI.Events.MenuEvent;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author teval
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private static Component comps[] = new Component[]{new CreateEvent(), reminderapp.ReminderApp.pagina, reminderapp.ReminderApp.retrasados, new Configurations(), new AdvancedOptions()};
    
    public Main() {
        initComponents();
        MenuEvent evt = new MenuEvent() {
            @Override
            public void menuSelected(int index) {
                Component comp = comps[index];
                if(index >= 0 && index < comps.length) showForm((comp));
            }
        };
        setIconImage(new ImageIcon("./system/reminder_cat.png").getImage());
        menuPrincipal.initMenu(evt);
        menuPrincipal.setSelected(1);
    }
    
    private void showForm(Component com){
        formsPane.removeAll();
        formsPane.add(com);
        formsPane.revalidate();
        formsPane.repaint();
    }
    
    public static void reinitComponents(){
        comps = new Component[]{new CreateEvent(), reminderapp.ReminderApp.pagina, reminderapp.ReminderApp.retrasados, new Configurations(), new AdvancedOptions()};
    }
    
    public void setPage(String pageName){
        if(pageName.equals("CreateEvent")){
            ((CreateEvent)comps[0]).isEditionMode();
            menuPrincipal.setSelected(0);
        }else if (pageName.equals("MyEvents")){
            menuPrincipal.setSelected(1);
        }
    }

    public static Component getComponent(String comp){
        if(comp.equals("Configurations")) return comps[3];
        return null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPrincipal = new UI.Components.Menu();
        formsPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        formsPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formsPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formsPane;
    private javax.swing.JPanel jPanel1;
    private UI.Components.Menu menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
